'use client';
import { Crown, Flame, Flag, Medal, Shield, Skull, Sparkles, Swords, Target, Trophy, type LucideIcon } from 'lucide-react';
import type { PlayerAward } from '@/lib/player-awards';
import type { AppLanguage } from '@/expo/lib/i18n/types';

type Style = { icon: LucideIcon; tone: string; panel: string; box: string };
const styles: Record<PlayerAward['kind'], Style> = {
  veteran: { icon: Medal, tone: 'text-sky-200', panel: 'border-sky-400/30 bg-gradient-to-br from-sky-500/15 via-card/70 to-background', box: 'border-sky-300/40 bg-sky-400/15' },
  eternal_second: { icon: Medal, tone: 'text-slate-100', panel: 'border-slate-300/30 bg-gradient-to-br from-slate-300/15 via-card/70 to-background', box: 'border-slate-200/40 bg-slate-200/15' },
  arena_king: { icon: Crown, tone: 'text-amber-200', panel: 'border-amber-400/35 bg-gradient-to-br from-amber-500/15 via-card/70 to-background', box: 'border-amber-300/40 bg-amber-400/15' },
  hitman: { icon: Target, tone: 'text-rose-200', panel: 'border-rose-400/30 bg-gradient-to-br from-rose-500/15 via-card/70 to-background', box: 'border-rose-300/40 bg-rose-400/15' },
  berserker: { icon: Flame, tone: 'text-orange-200', panel: 'border-orange-400/30 bg-gradient-to-br from-orange-500/15 via-card/70 to-background', box: 'border-orange-300/40 bg-orange-400/15' },
  archenemy: { icon: Skull, tone: 'text-red-200', panel: 'border-red-400/30 bg-gradient-to-br from-red-500/15 via-card/70 to-background', box: 'border-red-300/40 bg-red-400/15' },
  combo: { icon: Sparkles, tone: 'text-violet-200', panel: 'border-violet-400/30 bg-gradient-to-br from-violet-500/15 via-card/70 to-background', box: 'border-violet-300/40 bg-violet-400/15' },
  last_standing: { icon: Swords, tone: 'text-fuchsia-200', panel: 'border-fuchsia-400/30 bg-gradient-to-br from-fuchsia-500/15 via-card/70 to-background', box: 'border-fuchsia-300/40 bg-fuchsia-400/15' },
  concession: { icon: Flag, tone: 'text-lime-200', panel: 'border-lime-400/30 bg-gradient-to-br from-lime-500/15 via-card/70 to-background', box: 'border-lime-300/40 bg-lime-400/15' },
  true_skills: { icon: Shield, tone: 'text-teal-200', panel: 'border-teal-400/30 bg-gradient-to-br from-teal-500/15 via-card/70 to-background', box: 'border-teal-300/40 bg-teal-400/15' },
};
const titles: Record<PlayerAward['kind'], { it: string; en: string }> = { veteran: { it: 'Veterano', en: 'Veteran' }, eternal_second: { it: 'Eterno secondo', en: 'Eternal runner-up' }, arena_king: { it: 'Re dell’arena', en: 'Arena king' }, hitman: { it: 'Sicario', en: 'Hitman' }, berserker: { it: 'Berserker', en: 'Berserker' }, archenemy: { it: 'Archenemy', en: 'Archenemy' }, combo: { it: 'How about a magic trick?', en: 'How about a magic trick?' }, last_standing: { it: 'This will be a slaughter', en: 'This will be a slaughter' }, concession: { it: 'FF at 20', en: 'FF at 20' }, true_skills: { it: 'True display of skills', en: 'True display of skills' } };
const descriptions: Record<PlayerAward['kind'], { it: string; en: string }> = { veteran: { it: 'Più partite giocate', en: 'Most games played' }, eternal_second: { it: 'Più secondi posti', en: 'Most second places' }, arena_king: { it: 'Miglior win rate · minimo 5 partite', en: 'Best win rate · 5-game minimum' }, hitman: { it: 'Più eliminazioni di giocatori', en: 'Most player eliminations' }, berserker: { it: 'Più danni inflitti', en: 'Most damage dealt' }, archenemy: { it: 'Più volte sconfitto per primo', en: 'Most first eliminations' }, combo: { it: 'Più vittorie per combo', en: 'Most combo wins' }, last_standing: { it: 'Più vittorie Last Standing', en: 'Most Last Standing wins' }, concession: { it: 'Più vittorie per concessione', en: 'Most concession wins' }, true_skills: { it: 'Più vittorie alternate o other', en: 'Most alternate or other wins' } };
const medals = [
  'border-[#ffe89a] bg-[linear-gradient(135deg,#7a4b08_0%,#f6c94e_24%,#fff1a8_48%,#c58a19_72%,#6d4105_100%)] text-[#281700] shadow-[0_0_14px_rgba(246,201,78,.3)]',
  'border-[#f8fafc] bg-[linear-gradient(135deg,#64748b_0%,#dce3ec_27%,#fff_50%,#a6b2c2_76%,#526171_100%)] text-[#18212c] shadow-[0_0_12px_rgba(226,232,240,.22)]',
  'border-[#ffc184] bg-[linear-gradient(135deg,#71350f_0%,#cf772d_25%,#ffd09a_49%,#a94f19_74%,#5d290d_100%)] text-[#2b1005] shadow-[0_0_12px_rgba(205,112,42,.24)]',
];
export function PlayerAwards({ awards, language }: { awards: PlayerAward[]; language: AppLanguage }) {
  const groups = Object.values(awards.filter((award) => award.kind !== 'berserker').reduce((all, award) => { (all[award.kind] ??= []).push(award); return all; }, {} as Record<string, PlayerAward[]>));
  if (!groups.length) return null;
  return <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{groups.map((group) => { const visual = styles[group[0].kind]; const Icon = visual.icon; return <div key={group[0].kind} className={`relative overflow-hidden rounded-2xl border p-4 shadow-lg ${visual.panel}`}><Trophy className="absolute -right-3 -top-3 h-20 w-20 text-white/[0.035]"/><div className="relative mb-4 flex items-center gap-3 border-b border-white/10 pb-3"><span className={`grid h-10 w-10 place-items-center rounded-xl border ${visual.box}`}><Icon className={`h-5 w-5 ${visual.tone}`}/></span><div className="min-w-0 flex-1"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">{titles[group[0].kind][language]}</p><p className={`text-sm font-bold ${visual.tone}`}>{language === 'it' ? 'Top 3 giocatori' : 'Top 3 players'}</p></div><span className="rounded-full border border-white/10 bg-white/5 px-2 py-1 text-[10px] font-bold text-muted-foreground">{group.length}/3</span></div><p className="relative -mt-2 mb-3 text-xs text-muted-foreground">{descriptions[group[0].kind][language]}</p><div className="relative space-y-3">{group.map((award) => <div key={`${award.kind}:${award.rank}:${award.name}`} className="flex min-w-0 items-center gap-3 rounded-xl border border-white/10 bg-background/35 p-2.5"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full border text-xs font-black ${medals[award.rank - 1]}`}>{award.rank}</span><div className="min-w-0 flex-1"><p className="truncate font-semibold text-foreground">{award.name}</p><p className="text-[11px] text-muted-foreground">{language === 'it' ? 'Classifica giocatori' : 'Player ranking'}</p></div><span className={`shrink-0 text-sm font-black tabular-nums ${visual.tone}`}>{award.value}{award.kind === 'arena_king' ? '%' : ''}</span></div>)}</div></div>; })}</div>;
}
