'use client';
import { Crown, Flame, Flag, Medal, Shield, Skull, Sparkles, Swords, Target, Trophy, type LucideIcon } from 'lucide-react';
import type { PlayerAward } from '@/lib/player-awards';
import type { AppLanguage } from '@/expo/lib/i18n/types';

type Style = { icon: LucideIcon; tone: string; panel: string; box: string };
const styles: Record<PlayerAward['kind'], Style> = {
  veteran: { icon: Medal, tone: 'text-sky-200', panel: 'border-sky-400/30 bg-gradient-to-br from-sky-500/15 via-card/70 to-background', box: 'border-sky-300/40 bg-sky-400/15' },
  eternal_second: { icon: Medal, tone: 'text-slate-100', panel: 'border-slate-300/30 bg-gradient-to-br from-slate-300/15 via-card/70 to-background', box: 'border-slate-200/40 bg-slate-200/15' },
  arena_king: { icon: Crown, tone: 'text-amber-200', panel: 'border-amber-400/35 bg-gradient-to-br from-amber-500/15 via-card/70 to-background', box: 'border-amber-300/40 bg-amber-400/15' },
  hitman: { icon: Target, tone: 'text-rose-200', panel: 'border-rose-400/30 bg-gradient-to-br from-rose-500/15 via-card/70 to-background', box: 'border-rose-300/40 bg-rose-400/15' },
  berserker: { icon: Flame, tone: 'text-orange-200', panel: 'border-orange-400/30 bg-gradient-to-br from-orange-500/15 via-card/70 to-background', box: 'border-orange-300/40 bg-orange-400/15' },
  archenemy: { icon: Skull, tone: 'text-red-200', panel: 'border-red-400/30 bg-gradient-to-br from-red-500/15 via-card/70 to-background', box: 'border-red-300/40 bg-red-400/15' },
  combo: { icon: Sparkles, tone: 'text-violet-200', panel: 'border-violet-400/30 bg-gradient-to-br from-violet-500/15 via-card/70 to-background', box: 'border-violet-300/40 bg-violet-400/15' },
  last_standing: { icon: Swords, tone: 'text-fuchsia-200', panel: 'border-fuchsia-400/30 bg-gradient-to-br from-fuchsia-500/15 via-card/70 to-background', box: 'border-fuchsia-300/40 bg-fuchsia-400/15' },
  concession: { icon: Flag, tone: 'text-lime-200', panel: 'border-lime-400/30 bg-gradient-to-br from-lime-500/15 via-card/70 to-background', box: 'border-lime-300/40 bg-lime-400/15' },
  true_skills: { icon: Shield, tone: 'text-teal-200', panel: 'border-teal-400/30 bg-gradient-to-br from-teal-500/15 via-card/70 to-background', box: 'border-teal-300/40 bg-teal-400/15' },
};
const titles: Record<PlayerAward['kind'], { it: string; en: string }> = { veteran: { it: 'Veterano', en: 'Veteran' }, eternal_second: { it: 'Eterno secondo', en: 'Eternal runner-up' }, arena_king: { it: 'Re dell’arena', en: 'Arena king' }, hitman: { it: 'Sicario', en: 'Hitman' }, berserker: { it: 'Berserker', en: 'Berserker' }, archenemy: { it: 'Archenemy', en: 'Archenemy' }, combo: { it: 'How about a magic trick?', en: 'How about a magic trick?' }, last_standing: { it: 'This will be a slaughter', en: 'This will be a slaughter' }, concession: { it: 'FF at 20', en: 'FF at 20' }, true_skills: { it: 'True display of skills', en: 'True display of skills' } };
const descriptions: Record<PlayerAward['kind'], { it: string; en: string }> = { veteran: { it: 'Più partite giocate', en: 'Most games played' }, eternal_second: { it: 'Più secondi posti', en: 'Most second places' }, arena_king: { it: 'Miglior win rate · minimo 5 partite', en: 'Best win rate · 5-game minimum' }, hitman: { it: 'Più eliminazioni di giocatori', en: 'Most player eliminations' }, berserker: { it: 'Più danni inflitti', en: 'Most damage dealt' }, archenemy: { it: 'Più volte sconfitto per primo', en: 'Most first eliminations' }, combo: { it: 'Più vittorie per combo', en: 'Most combo wins' }, last_standing: { it: 'Più vittorie Last Standing', en: 'Most Last Standing wins' }, concession: { it: 'Più vittorie per concessione', en: 'Most concession wins' }, true_skills: { it: 'Più vittorie alternate o other', en: 'Most alternate or other wins' } };
const medals = ['bg-yellow-300 text-yellow-950', 'bg-slate-200 text-slate-950', 'bg-orange-600 text-white'];
export function PlayerAwards({ awards, language }: { awards: PlayerAward[]; language: AppLanguage }) {
  const groups = Object.values(awards.reduce((all, award) => { (all[award.kind] ??= []).push(award); return all; }, {} as Record<string, PlayerAward[]>));
  if (!groups.length) return null;
  return <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{groups.map((group) => { const visual = styles[group[0].kind]; const Icon = visual.icon; return <div key={group[0].kind} className={`relative overflow-hidden rounded-2xl border p-4 shadow-lg ${visual.panel}`}><Trophy className="absolute -right-3 -top-3 h-20 w-20 text-white/[0.035]"/><div className="relative mb-3 flex items-center gap-3 border-b border-white/10 pb-3"><span className={`grid h-10 w-10 place-items-center rounded-xl border ${visual.box}`}><Icon className={`h-5 w-5 ${visual.tone}`}/></span><div><p className={`font-bold ${visual.tone}`}>{titles[group[0].kind][language]}</p><p className="text-xs text-muted-foreground">{descriptions[group[0].kind][language]} · {language === 'it' ? 'Top 3 giocatori' : 'Top 3 players'}</p></div></div><div className="relative space-y-2">{group.map((award) => <div key={`${award.kind}:${award.rank}:${award.name}`} className="flex items-center gap-3 rounded-xl border border-white/5 bg-black/15 p-2.5"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-black ${medals[award.rank - 1]}`}>{award.rank}</span><span className="min-w-0 flex-1 truncate font-semibold text-foreground">{award.name}</span><span className={`flex items-center gap-1 font-black ${visual.tone}`}><Icon className="h-3.5 w-3.5"/>{award.value}{award.kind === 'arena_king' ? '%' : ''}</span></div>)}</div></div>; })}</div>;
}
