'use client';
import { Crown, Flame, Flag, HeartPulse, Medal, Shield, Skull, Sparkles, Swords, Target, Trophy, type LucideIcon } from 'lucide-react';
import type { PlayerAward } from '@/lib/player-awards';
import type { AppLanguage } from '@/expo/lib/i18n/types';

type Style = { icon: LucideIcon; tone: string; panel: string; box: string };
const styles: Record<PlayerAward['kind'], Style> = {
  veteran: { icon: Medal, tone: 'text-sky-200', panel: 'border-sky-400/30 bg-gradient-to-br from-sky-500/15 via-card/70 to-background', box: 'border-sky-300/40 bg-sky-400/15' },
  eternal_second: { icon: Medal, tone: 'text-slate-100', panel: 'border-slate-300/30 bg-gradient-to-br from-slate-300/15 via-card/70 to-background', box: 'border-slate-200/40 bg-slate-200/15' },
  arena_king: { icon: Crown, tone: 'text-amber-200', panel: 'border-amber-400/35 bg-gradient-to-br from-amber-500/15 via-card/70 to-background', box: 'border-amber-300/40 bg-amber-400/15' },
  hitman: { icon: Target, tone: 'text-rose-200', panel: 'border-rose-400/30 bg-gradient-to-br from-rose-500/15 via-card/70 to-background', box: 'border-rose-300/40 bg-rose-400/15' },
  berserker: { icon: Flame, tone: 'text-orange-200', panel: 'border-orange-400/30 bg-gradient-to-br from-orange-500/15 via-card/70 to-background', box: 'border-orange-300/40 bg-orange-400/15' },
  archenemy: { icon: Skull, tone: 'text-red-200', panel: 'border-red-400/30 bg-gradient-to-br from-red-500/15 via-card/70 to-background', box: 'border-red-300/40 bg-red-400/15' },
  combo: { icon: Sparkles, tone: 'text-violet-200', panel: 'border-violet-400/30 bg-gradient-to-br from-violet-500/15 via-card/70 to-background', box: 'border-violet-300/40 bg-violet-400/15' },
  last_standing: { icon: Swords, tone: 'text-fuchsia-200', panel: 'border-fuchsia-400/30 bg-gradient-to-br from-fuchsia-500/15 via-card/70 to-background', box: 'border-fuchsia-300/40 bg-fuchsia-400/15' },
  concession: { icon: Flag, tone: 'text-lime-200', panel: 'border-lime-400/30 bg-gradient-to-br from-lime-500/15 via-card/70 to-background', box: 'border-lime-300/40 bg-lime-400/15' },
  true_skills: { icon: Shield, tone: 'text-teal-200', panel: 'border-teal-400/30 bg-gradient-to-br from-teal-500/15 via-card/70 to-background', box: 'border-teal-300/40 bg-teal-400/15' },
  healing_master: { icon: HeartPulse, tone: 'text-emerald-200', panel: 'border-emerald-400/30 bg-gradient-to-br from-emerald-500/15 via-card/70 to-background', box: 'border-emerald-300/40 bg-emerald-400/15' },
  beginners_luck: { icon: Crown, tone: 'text-cyan-200', panel: 'border-cyan-400/30 bg-gradient-to-br from-cyan-500/15 via-card/70 to-background', box: 'border-cyan-300/40 bg-cyan-400/15' },
};
const titles: Record<PlayerAward['kind'], { it: string; en: string }> = { veteran: { it: 'Veterano', en: 'Veteran' }, eternal_second: { it: 'Eterno secondo', en: 'Eternal runner-up' }, arena_king: { it: 'Re dell’arena', en: 'Arena king' }, hitman: { it: 'Sicario', en: 'Hitman' }, berserker: { it: 'Berserker', en: 'Berserker' }, archenemy: { it: 'Archenemy', en: 'Archenemy' }, combo: { it: 'How about a magic trick?', en: 'How about a magic trick?' }, last_standing: { it: 'This will be a slaughter', en: 'This will be a slaughter' }, concession: { it: 'FF at 20', en: 'FF at 20' }, true_skills: { it: 'True display of skills', en: 'True display of skills' }, healing_master: { it: 'Healing Master', en: 'Healing Master' }, beginners_luck: { it: 'Beginner’s luck', en: 'Beginner’s luck' } };
const descriptions: Record<PlayerAward['kind'], { it: string; en: string }> = { veteran: { it: 'Più partite giocate', en: 'Most games played' }, eternal_second: { it: 'Più secondi posti', en: 'Most second places' }, arena_king: { it: 'Miglior win rate · minimo 5 partite', en: 'Best win rate · 5-game minimum' }, hitman: { it: 'Più eliminazioni di giocatori', en: 'Most player eliminations' }, berserker: { it: 'Più danni inflitti', en: 'Most damage dealt' }, archenemy: { it: 'Più volte sconfitto per primo', en: 'Most first eliminations' }, combo: { it: 'Più vittorie per combo', en: 'Most combo wins' }, last_standing: { it: 'Più vittorie Last Standing', en: 'Most Last Standing wins' }, concession: { it: 'Più vittorie per concessione', en: 'Most concession wins' }, true_skills: { it: 'Più vittorie alternate o other', en: 'Most alternate or other wins' }, healing_master: { it: 'Più punti vita guadagnati in una partita', en: 'Most life gained in a single match' }, beginners_luck: { it: 'Più volte primo giocatore', en: 'Most starting-player selections' } };
const medals = [
  'border-amber-300/25 bg-gradient-to-r from-[#17161a] via-[#282318] to-[#17161a] text-foreground',
  'border-slate-300/25 bg-gradient-to-r from-[#17161a] via-[#22272e] to-[#17161a] text-foreground',
  'border-orange-300/25 bg-gradient-to-r from-[#17161a] via-[#28201b] to-[#17161a] text-foreground',
];
const medalBadges = [
  'border-amber-200/70 bg-gradient-to-br from-amber-200 via-amber-400 to-amber-700 text-[#251a05]',
  'border-slate-100/80 bg-gradient-to-br from-white via-slate-300 to-slate-500 text-[#17202a]',
  'border-orange-200/70 bg-gradient-to-br from-orange-200 via-orange-500 to-orange-800 text-[#291307]',
];
export function PlayerAwards({ awards, language }: { awards: PlayerAward[]; language: AppLanguage }) {
  const groups = Object.values(awards.filter((award) => award.kind !== 'berserker').reduce((all, award) => { (all[award.kind] ??= []).push(award); return all; }, {} as Record<string, PlayerAward[]>));
  if (!groups.length) return null;
  return <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{groups.map((group) => { const visual = styles[group[0].kind]; const Icon = visual.icon; return <div key={group[0].kind} className={`relative overflow-hidden rounded-2xl border p-4 shadow-lg ${visual.panel}`}><Trophy className="absolute -right-3 -top-3 h-20 w-20 text-white/[0.035]"/><div className="relative mb-4 flex items-center gap-3 border-b border-white/10 pb-3"><span className={`grid h-10 w-10 place-items-center rounded-xl border ${visual.box}`}><Icon className={`h-5 w-5 ${visual.tone}`}/></span><div className="min-w-0 flex-1"><p className="text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">{titles[group[0].kind][language]}</p><p className={`text-sm font-bold ${visual.tone}`}>{language === 'it' ? 'Top 3 giocatori' : 'Top 3 players'}</p></div><span className="rounded-full border border-white/10 bg-white/5 px-2 py-1 text-[10px] font-bold text-muted-foreground">{group.length}/3</span></div><p className="relative -mt-2 mb-3 text-xs text-muted-foreground">{descriptions[group[0].kind][language]}</p><div className="relative space-y-3">{group.map((award) => { const shape = award.rank === 1 ? 'polygon(50% 0%,62% 26%,91% 12%,80% 42%,100% 50%,80% 61%,91% 89%,62% 76%,50% 100%,38% 76%,9% 89%,20% 61%,0% 50%,20% 42%,9% 12%,38% 26%)' : award.rank === 2 ? 'polygon(20% 0%,80% 0%,100% 22%,88% 78%,50% 100%,12% 78%,0% 22%)' : 'polygon(50% 0%,100% 50%,50% 100%,0% 50%)'; return <div key={`${award.kind}:${award.rank}:${award.name}`} className={`relative flex min-w-0 items-center gap-3 rounded-xl border p-2.5 shadow-sm ${medals[award.rank - 1]}`}><span aria-label={`#${award.rank}`} style={{ clipPath: shape }} className={`relative grid h-10 w-10 shrink-0 place-items-center text-xs font-black drop-shadow-sm ${medalBadges[award.rank - 1]}`}><span aria-hidden="true" style={{ clipPath: shape }} className="absolute inset-[3px] border border-white/45 bg-white/10"/><span className="relative z-10">{award.rank}</span></span><div className="min-w-0 flex-1"><p className="truncate font-bold">{award.name}</p><p className="text-[11px] text-muted-foreground">{language === 'it' ? 'Classifica giocatori' : 'Player ranking'}</p></div><span className={`shrink-0 text-sm font-black tabular-nums ${visual.tone}`}>{award.value}{award.kind === 'arena_king' ? '%' : ''}</span></div>; })}</div></div>; })}</div>;
}
