import { StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { PhyrexianPanel } from '@/components/ui/phyrexian-panel';
import { colors, spacing } from '@/constants/theme';
import type { PlayerAward, PlayerAwardKind } from '@/lib/player-awards';

const meta: Record<PlayerAwardKind, { it: string; en: string; hintIt: string; hintEn: string; icon: keyof typeof Ionicons.glyphMap; color: string }> = {
  veteran: { it: 'Veterano', en: 'Veteran', hintIt: 'Più partite giocate', hintEn: 'Most games played', icon: 'medal-outline', color: '#7dd3fc' }, eternal_second: { it: 'Eterno secondo', en: 'Eternal runner-up', hintIt: 'Più secondi posti', hintEn: 'Most second places', icon: 'ribbon-outline', color: '#e2e8f0' }, arena_king: { it: 'Re dell’arena', en: 'Arena king', hintIt: 'Miglior win rate · minimo 5 partite', hintEn: 'Best win rate · 5-game minimum', icon: 'trophy-outline', color: '#fcd34d' }, hitman: { it: 'Sicario', en: 'Hitman', hintIt: 'Più eliminazioni', hintEn: 'Most eliminations', icon: 'locate-outline', color: '#fda4af' }, berserker: { it: 'Berserker', en: 'Berserker', hintIt: 'Più danni inflitti', hintEn: 'Most damage dealt', icon: 'flame-outline', color: '#fdba74' }, archenemy: { it: 'Archenemy', en: 'Archenemy', hintIt: 'Più volte eliminato per primo', hintEn: 'Most first eliminations', icon: 'skull-outline', color: '#fca5a5' }, combo: { it: 'How about a magic trick?', en: 'How about a magic trick?', hintIt: 'Più vittorie per combo', hintEn: 'Most combo wins', icon: 'sparkles-outline', color: '#c4b5fd' }, last_standing: { it: 'This will be a slaughter', en: 'This will be a slaughter', hintIt: 'Più vittorie Last Standing', hintEn: 'Most Last Standing wins', icon: 'flash-outline', color: '#f0abfc' }, concession: { it: 'FF at 20', en: 'FF at 20', hintIt: 'Più vittorie per concessione', hintEn: 'Most concession wins', icon: 'flag-outline', color: '#bef264' }, true_skills: { it: 'True display of skills', en: 'True display of skills', hintIt: 'Più vittorie alternate o other', hintEn: 'Most alternate or other wins', icon: 'shield-checkmark-outline', color: '#5eead4' },
};
const medal = ['#f4c95d', '#c5ced8', '#c8874a'];
export function PlayerAwardsTab({ awards, language }: { awards: PlayerAward[]; language: 'it' | 'en' }) {
  const groups = Array.from(awards.reduce((map, award) => { const rows = map.get(award.kind) ?? []; rows.push(award); map.set(award.kind, rows); return map; }, new Map<PlayerAwardKind, PlayerAward[]>()).values());
  if (!groups.length) return <PhyrexianPanel style={styles.empty}><Text style={styles.emptyText}>{language === 'it' ? 'Nessun award giocatore disponibile' : 'No player awards yet'}</Text></PhyrexianPanel>;
  return <View style={styles.list}>{groups.map((group) => { const item = meta[group[0].kind]; return <PhyrexianPanel key={group[0].kind} style={[styles.panel, { borderColor: `${item.color}55` }]}><View style={styles.header}><Ionicons name={item.icon} size={21} color={item.color} /><View style={styles.grow}><Text style={[styles.title, { color: item.color }]}>{language === 'it' ? item.it : item.en}</Text><Text style={styles.hint}>{language === 'it' ? item.hintIt : item.hintEn}</Text></View></View>{group.map((award) => <View key={`${award.kind}:${award.rank}:${award.name}`} style={styles.row}><View style={[styles.rank, { backgroundColor: medal[award.rank - 1] }]}><Text style={styles.rankText}>{award.rank}</Text></View><Text style={styles.name} numberOfLines={1}>{award.name}</Text><Text style={[styles.value, { color: item.color }]}>{award.value}{award.kind === 'arena_king' ? '%' : ''}</Text></View>)}</PhyrexianPanel>; })}</View>;
}
const styles = StyleSheet.create({ list: { gap: spacing.md }, panel: { gap: spacing.sm, padding: spacing.md }, header: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.borderSoft, paddingBottom: spacing.sm }, grow: { flex: 1 }, title: { fontSize: 16, fontWeight: '900' }, hint: { color: colors.muted, fontSize: 12, marginTop: 2 }, row: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, borderRadius: 10, backgroundColor: colors.surfaceMuted, padding: 9 }, rank: { alignItems: 'center', justifyContent: 'center', width: 26, height: 26, borderRadius: 13 }, rankText: { color: '#111827', fontSize: 12, fontWeight: '900' }, name: { color: colors.foreground, flex: 1, fontWeight: '700' }, value: { fontSize: 16, fontWeight: '900' }, empty: { alignItems: 'center' }, emptyText: { color: colors.muted } });
