-- Additive runtime controls. Existing 8.1 clients do not read these tables and
-- continue to use the existing API and schema unchanged.
CREATE TABLE IF NOT EXISTS public.app_runtime_configuration (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  minimum_supported_version text NOT NULL DEFAULT '8.1.0',
  recommended_version text NOT NULL DEFAULT '8.2.0',
  maintenance_message_it text,
  maintenance_message_en text,
  feature_flags jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(feature_flags) = 'object'),
  release_notes jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(release_notes) = 'array'),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.app_runtime_configuration ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.app_runtime_configuration FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.app_runtime_configuration TO service_role;

INSERT INTO public.app_runtime_configuration (
  id,
  minimum_supported_version,
  recommended_version,
  feature_flags,
  release_notes
)
VALUES (
  true,
  '8.1.0',
  '8.2.0',
  '{"lastStanding": true, "deckWizardSearch": true}'::jsonb,
  '[{"version":"8.2.0","it":"Ricerca mazzi nel live, Last Standing e maggiore osservabilità.","en":"Live-game deck search, Last Standing, and improved observability."}]'::jsonb
)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.notification_delivery_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id uuid,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  provider text NOT NULL DEFAULT 'expo',
  status text NOT NULL CHECK (status IN ('queued', 'sent', 'retryable_error', 'permanent_error')),
  provider_code text,
  latency_ms integer CHECK (latency_ms IS NULL OR latency_ms >= 0),
  attempted_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.notification_delivery_attempts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.notification_delivery_attempts FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.notification_delivery_attempts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.notification_delivery_attempts_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS notification_delivery_attempts_attempted_at_idx
  ON public.notification_delivery_attempts (attempted_at DESC);
CREATE INDEX IF NOT EXISTS notification_delivery_attempts_user_id_attempted_at_idx
  ON public.notification_delivery_attempts (user_id, attempted_at DESC)
  WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS notification_delivery_attempts_status_attempted_at_idx
  ON public.notification_delivery_attempts (status, attempted_at DESC);

COMMENT ON TABLE public.app_runtime_configuration IS
  'Server-owned client compatibility, staged feature flags, and localized release notes.';
COMMENT ON TABLE public.notification_delivery_attempts IS
  'Service-role-only delivery telemetry without push tokens or message bodies.';
